-- Mi Colacteos / Registro de Beneficios
-- Run this first in Supabase SQL Editor, then run seed.sql.

create extension if not exists pgcrypto;

create table if not exists public.benefit_registrations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  data_processing_authorized boolean not null,
  commercial_communications_authorized boolean not null default false,
  preferred_contact_channel varchar(120),
  full_name varchar(180) not null,
  document_type varchar(80) not null,
  document_number varchar(40) not null,
  phone varchar(15) not null,
  email varchar(254) not null,
  birth_date date,
  zone_type varchar(20) not null check (zone_type in ('Barrio', 'Vereda')),
  place_name varchar(180) not null,
  division_name varchar(180),
  road_type varchar(80) not null,
  road_number varchar(40) not null,
  road_suffix varchar(40),
  secondary_number varchar(40) not null,
  address_extra varchar(180),
  full_address varchar(700) not null,
  city varchar(120) not null default 'Pasto',
  department varchar(120) not null default 'Nariño',
  country varchar(120) not null default 'Colombia',
  latitude numeric(10,7),
  longitude numeric(10,7),
  source varchar(80) not null default 'nextjs-web',
  constraint treatment_required check (data_processing_authorized = true),
  constraint phone_format check (phone ~ '^[0-9]{7,15}$'),
  constraint latitude_range check (latitude is null or latitude between -90 and 90),
  constraint longitude_range check (longitude is null or longitude between -180 and 180)
);

create index if not exists benefit_registrations_created_at_idx
  on public.benefit_registrations (created_at desc);
create index if not exists benefit_registrations_document_idx
  on public.benefit_registrations (document_number);
create index if not exists benefit_registrations_email_idx
  on public.benefit_registrations (lower(email));

create table if not exists public.territorial_catalog (
  id bigint generated by default as identity primary key,
  place_type varchar(20) not null check (place_type in ('Barrio', 'Vereda')),
  place_name varchar(180) not null,
  division_name varchar(180),
  created_at timestamptz not null default now(),
  unique (place_type, place_name)
);

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.benefit_registrations enable row level security;
alter table public.territorial_catalog enable row level security;
alter table public.app_admins enable row level security;

-- Public catalog: read-only from the browser.
drop policy if exists "territorial catalog public read" on public.territorial_catalog;
create policy "territorial catalog public read"
on public.territorial_catalog
for select
to anon, authenticated
using (true);

-- Admin helper used by RLS.
create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_app_admin() from public;
grant execute on function public.is_app_admin() to authenticated;

-- Admin users can see only their own admin membership row.
drop policy if exists "admins can read own membership" on public.app_admins;
create policy "admins can read own membership"
on public.app_admins
for select
to authenticated
using (user_id = auth.uid());

-- Personal registration data is never readable by anon users.
drop policy if exists "admins can read registrations" on public.benefit_registrations;
create policy "admins can read registrations"
on public.benefit_registrations
for select
to authenticated
using (public.is_app_admin());

-- Least privilege grants.
revoke all on public.benefit_registrations from anon;
revoke all on public.app_admins from anon;
grant select on public.territorial_catalog to anon, authenticated;
grant select on public.benefit_registrations to authenticated;
grant select on public.app_admins to authenticated;
grant all on public.benefit_registrations to service_role;
grant all on public.territorial_catalog to service_role;
grant all on public.app_admins to service_role;

-- IMPORTANT: anonymous users do NOT get INSERT permission directly.
-- The public form posts to /api/register, which validates CAPTCHA and then
-- inserts server-side using SUPABASE_SERVICE_ROLE_KEY.

-- Bootstrap an administrator AFTER creating the user in Supabase Auth:
-- insert into public.app_admins (user_id)
-- select id from auth.users where email = 'admin@your-domain.com'
-- on conflict (user_id) do nothing;
