-- Territorial fallback catalog migrated from the Power Pages export.
-- division_name is NULL because the export only contained the fallback place names, not the Dataverse relationship rows.

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Barrio','Achalay',NULL),
  ('Barrio','Agualongo',NULL),
  ('Barrio','Aire Libre',NULL),
  ('Barrio','Alameda',NULL),
  ('Barrio','Alameda II',NULL),
  ('Barrio','Albergue Del Sol',NULL),
  ('Barrio','Alhambra',NULL),
  ('Barrio','Altamira',NULL),
  ('Barrio','Altamira – San Vicente',NULL),
  ('Barrio','Altavista',NULL),
  ('Barrio','Alto Juanoy',NULL),
  ('Barrio','Altos De Chapalito I',NULL),
  ('Barrio','Altos De Chapalito II',NULL),
  ('Barrio','Altos De Chapalito III',NULL),
  ('Barrio','Altos De La Carolina',NULL),
  ('Barrio','Altos de la Colina',NULL),
  ('Barrio','Altos De Lorenzo',NULL),
  ('Barrio','Altos Del Campo',NULL),
  ('Barrio','Anganoy',NULL),
  ('Barrio','Antonio Nariño',NULL),
  ('Barrio','Aquine Alto',NULL),
  ('Barrio','Aquine I',NULL),
  ('Barrio','Aquine II',NULL),
  ('Barrio','Aquine III',NULL),
  ('Barrio','Aquine IV',NULL),
  ('Barrio','Aquine Reservado',NULL),
  ('Barrio','Aranda',NULL),
  ('Barrio','Arcos Iris',NULL),
  ('Barrio','Arnulfo Guerrero',NULL),
  ('Barrio','Atahualpa',NULL),
  ('Barrio','Avenida Aranda',NULL),
  ('Barrio','Avenida Boyacá',NULL),
  ('Barrio','Avenida Champagnath',NULL),
  ('Barrio','Avenida Colombia',NULL),
  ('Barrio','Avenida Idema',NULL),
  ('Barrio','Avenida Los Estudiantes',NULL),
  ('Barrio','Avenida Oriental',NULL),
  ('Barrio','Avenida Oriental Rio Pasto',NULL),
  ('Barrio','Avenida Panamericana',NULL),
  ('Barrio','Avenida Santander',NULL),
  ('Barrio','Bachue',NULL),
  ('Barrio','Balcones de Mariluz',NULL),
  ('Barrio','Balcones Del Este',NULL),
  ('Barrio','Belalcázar',NULL),
  ('Barrio','Bella Vista',NULL),
  ('Barrio','Bello Horizonte',NULL),
  ('Barrio','Belén',NULL),
  ('Barrio','Bernal',NULL),
  ('Barrio','Betania',NULL),
  ('Barrio','Bombona',NULL),
  ('Barrio','Briceño',NULL),
  ('Barrio','Buenos Aires',NULL),
  ('Barrio','Caicedo',NULL),
  ('Barrio','Caicedonia',NULL),
  ('Barrio','Calatrava',NULL),
  ('Barrio','Camilo Torres',NULL),
  ('Barrio','Camino Real',NULL),
  ('Barrio','Campiña De Oriente',NULL),
  ('Barrio','Cantarana',NULL),
  ('Barrio','Capusigra',NULL),
  ('Barrio','Caracha',NULL),
  ('Barrio','Carlos Pizarro',NULL),
  ('Barrio','Casa Bella',NULL),
  ('Barrio','Casa Loma',NULL),
  ('Barrio','Castilla',NULL),
  ('Barrio','Castillos Del Norte',NULL),
  ('Barrio','Cementerio',NULL),
  ('Barrio','Centenario',NULL),
  ('Barrio','Centro',NULL),
  ('Barrio','Chambú I',NULL),
  ('Barrio','Chambú II',NULL),
  ('Barrio','Chapal',NULL),
  ('Barrio','Chapal II',NULL),
  ('Barrio','Chapultepec',NULL),
  ('Barrio','Chico',NULL),
  ('Barrio','Chile',NULL),
  ('Barrio','Ciudad Jardín',NULL),
  ('Barrio','Ciudad Real',NULL),
  ('Barrio','Coliseo Cubierto',NULL),
  ('Barrio','Colonial',NULL),
  ('Barrio','Colpatria',NULL),
  ('Barrio','Colón',NULL),
  ('Barrio','Condominio Bellavista',NULL),
  ('Barrio','Condominio Morasurco',NULL),
  ('Barrio','Condominio Santiago',NULL),
  ('Barrio','Conjunto El Parque',NULL),
  ('Barrio','Conjunto San Diego',NULL),
  ('Barrio','Conjunto Torobajo',NULL),
  ('Barrio','Cooperativa Popular Nariñense',NULL),
  ('Barrio','Corazón De Jesús',NULL),
  ('Barrio','Corazón De Jesús II',NULL),
  ('Barrio','Cra 27 A Del Barrio Centenario',NULL),
  ('Barrio','Cujacal Bajo',NULL),
  ('Barrio','Destechados',NULL),
  ('Barrio','Doce De Octubre I',NULL),
  ('Barrio','Doce De Octubre II',NULL),
  ('Barrio','El Aljibe',NULL),
  ('Barrio','El Bosque',NULL),
  ('Barrio','El Calvario',NULL),
  ('Barrio','El Cerámico',NULL)
on conflict (place_type, place_name) do nothing;

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Barrio','El Churo',NULL),
  ('Barrio','El Cilindro',NULL),
  ('Barrio','El Común',NULL),
  ('Barrio','El Corralito',NULL),
  ('Barrio','El Dorado',NULL),
  ('Barrio','El Edén',NULL),
  ('Barrio','El Ejido',NULL),
  ('Barrio','El Estadio',NULL),
  ('Barrio','El Futuro',NULL),
  ('Barrio','El Libertador',NULL),
  ('Barrio','El Manantial',NULL),
  ('Barrio','El Mirador',NULL),
  ('Barrio','El Olivo',NULL),
  ('Barrio','El Paraíso',NULL),
  ('Barrio','El Parque',NULL),
  ('Barrio','El Pilar',NULL),
  ('Barrio','El Polvorín',NULL),
  ('Barrio','El Portal De Aranda',NULL),
  ('Barrio','El Portal Del Norte',NULL),
  ('Barrio','El Portalito',NULL),
  ('Barrio','El Porvenir',NULL),
  ('Barrio','El Prado',NULL),
  ('Barrio','El Progreso',NULL),
  ('Barrio','El Recuerdo',NULL),
  ('Barrio','El Refugio',NULL),
  ('Barrio','El Remanso',NULL),
  ('Barrio','El Remanso del Norte',NULL),
  ('Barrio','El Rincón De La Aurora',NULL),
  ('Barrio','El Rincón De La Panamericana',NULL),
  ('Barrio','El Rincón De Pasto',NULL),
  ('Barrio','El Rincón Del Rosario',NULL),
  ('Barrio','El Rosario',NULL),
  ('Barrio','El Tejar',NULL),
  ('Barrio','El Triunfo',NULL),
  ('Barrio','Emilio Botero I',NULL),
  ('Barrio','Emilio Botero II',NULL),
  ('Barrio','Emilio Botero III',NULL),
  ('Barrio','Emilio Botero IV',NULL),
  ('Barrio','Figueroa',NULL),
  ('Barrio','Francisco De La Villota',NULL),
  ('Barrio','Fray Ezequiel Moreno Díaz',NULL),
  ('Barrio','Fátima',NULL),
  ('Barrio','Gilberto Pabón',NULL),
  ('Barrio','Granada I',NULL),
  ('Barrio','Granada II',NULL),
  ('Barrio','Granada III',NULL),
  ('Barrio','Granada IV',NULL),
  ('Barrio','Gualcala',NULL),
  ('Barrio','Gualcaloma',NULL),
  ('Barrio','Guamuez',NULL),
  ('Barrio','Hospital Civil',NULL),
  ('Barrio','Hullaguanga',NULL),
  ('Barrio','iAlejandría',NULL),
  ('Barrio','Inem',NULL),
  ('Barrio','Javeriano',NULL),
  ('Barrio','Jerusalén',NULL),
  ('Barrio','Jorge Giraldo',NULL),
  ('Barrio','José Antonio Galán',NULL),
  ('Barrio','José Ignacio Zarama',NULL),
  ('Barrio','Juan Pablo II',NULL),
  ('Barrio','Juan XXIII',NULL),
  ('Barrio','Juanoy',NULL),
  ('Barrio','Julián Bucheli',NULL),
  ('Barrio','La Aurora',NULL),
  ('Barrio','La Carolina',NULL),
  ('Barrio','La Castellana',NULL),
  ('Barrio','La Colina',NULL),
  ('Barrio','La Cruz',NULL),
  ('Barrio','La Cuesta',NULL),
  ('Barrio','La Esmeralda',NULL),
  ('Barrio','La Esperanza',NULL),
  ('Barrio','La Estrella',NULL),
  ('Barrio','La Floresta',NULL),
  ('Barrio','La Florida',NULL),
  ('Barrio','La Gran Colombia',NULL),
  ('Barrio','La Josefina',NULL),
  ('Barrio','La Lomita',NULL),
  ('Barrio','La Minga',NULL),
  ('Barrio','La Palma',NULL),
  ('Barrio','La Panadería',NULL),
  ('Barrio','La Paz',NULL),
  ('Barrio','La Pradera',NULL),
  ('Barrio','La Primavera',NULL),
  ('Barrio','La Riviera',NULL),
  ('Barrio','La Rosa',NULL),
  ('Barrio','La Vega',NULL),
  ('Barrio','La Victoria',NULL),
  ('Barrio','Las Acacias',NULL),
  ('Barrio','Las Américas',NULL),
  ('Barrio','Las Brisas',NULL),
  ('Barrio','Las Camelias',NULL),
  ('Barrio','Las Cuadras',NULL),
  ('Barrio','Las Ferias',NULL),
  ('Barrio','Las Lajas',NULL),
  ('Barrio','Las lunas I',NULL),
  ('Barrio','las lunas II',NULL),
  ('Barrio','Las Margaritas',NULL),
  ('Barrio','Las Mercedes',NULL),
  ('Barrio','Las Orquídeas',NULL),
  ('Barrio','Las Violetas I',NULL)
on conflict (place_type, place_name) do nothing;

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Barrio','Las Violetas II',NULL),
  ('Barrio','Las Violetas III',NULL),
  ('Barrio','Las Violetas IV',NULL),
  ('Barrio','Laureano Gómez',NULL),
  ('Barrio','Libertad',NULL),
  ('Barrio','Loma Del Carmen (Marquetalia)',NULL),
  ('Barrio','Lorenzo De Aldana',NULL),
  ('Barrio','Los Abedules',NULL),
  ('Barrio','Los Alcázares',NULL),
  ('Barrio','Los Andes',NULL),
  ('Barrio','Los Balcones',NULL),
  ('Barrio','Los Cristales',NULL),
  ('Barrio','Los Dos Puentes',NULL),
  ('Barrio','Los Elíseos',NULL),
  ('Barrio','Los Frailejones',NULL),
  ('Barrio','Los Fundadores',NULL),
  ('Barrio','Los Hexágonos',NULL),
  ('Barrio','Los Héroes',NULL),
  ('Barrio','Los Laureles',NULL),
  ('Barrio','Los Nogales',NULL),
  ('Barrio','Los Olivos',NULL),
  ('Barrio','Los Pinos',NULL),
  ('Barrio','Los Robles',NULL),
  ('Barrio','Los Sauces',NULL),
  ('Barrio','Los Urapanes',NULL),
  ('Barrio','Los Álamos',NULL),
  ('Barrio','Luis Brand',NULL),
  ('Barrio','Luis Carlos Galán',NULL),
  ('Barrio','Madrigal',NULL),
  ('Barrio','Manaca',NULL),
  ('Barrio','Marcos De La Rosa',NULL),
  ('Barrio','Maridiaz',NULL),
  ('Barrio','Mariluz I',NULL),
  ('Barrio','Mariluz II',NULL),
  ('Barrio','Mariluz III',NULL),
  ('Barrio','Marquetalia',NULL),
  ('Barrio','Marsella',NULL),
  ('Barrio','María Isabel I',NULL),
  ('Barrio','María Isabel II',NULL),
  ('Barrio','María Isabel III',NULL),
  ('Barrio','María Paz',NULL),
  ('Barrio','María Paz II',NULL),
  ('Barrio','Medardo Bucheli',NULL),
  ('Barrio','Mercedario',NULL),
  ('Barrio','Mijitayo',NULL),
  ('Barrio','Mijitayo Bajo',NULL),
  ('Barrio','Mijitayo II',NULL),
  ('Barrio','Mirador De Niza',NULL),
  ('Barrio','Mirador de San Juan',NULL),
  ('Barrio','Miraflores I',NULL),
  ('Barrio','Miraflores II',NULL),
  ('Barrio','Miravalle',NULL),
  ('Barrio','Monserrat',NULL),
  ('Barrio','Montemor',NULL),
  ('Barrio','Morasurco',NULL),
  ('Barrio','Navarrete',NULL),
  ('Barrio','Niza I',NULL),
  ('Barrio','Niza II',NULL),
  ('Barrio','Niza III',NULL),
  ('Barrio','Niño Jesús De Praga',NULL),
  ('Barrio','Normandía',NULL),
  ('Barrio','Nueva Aranda',NULL),
  ('Barrio','Nueva Colombia',NULL),
  ('Barrio','Nuevo Amanecer',NULL),
  ('Barrio','Nuevo Horizonte',NULL),
  ('Barrio','Nuevo Sol',NULL),
  ('Barrio','Ocho De Marzo',NULL),
  ('Barrio','Palermo',NULL),
  ('Barrio','Panamericano',NULL),
  ('Barrio','Panamericano I',NULL),
  ('Barrio','Panamericano II',NULL),
  ('Barrio','Pandiaco',NULL),
  ('Barrio','Parana',NULL),
  ('Barrio','Parque Bolívar',NULL),
  ('Barrio','Parque De Baviera',NULL),
  ('Barrio','Parque Infantil',NULL),
  ('Barrio','Pie De Cuesta',NULL),
  ('Barrio','Pinar Del Rio',NULL),
  ('Barrio','Pinos Del Norte',NULL),
  ('Barrio','Popular',NULL),
  ('Barrio','Portal de la Colina',NULL),
  ('Barrio','Portal De La Colina',NULL),
  ('Barrio','Potrerillo',NULL),
  ('Barrio','Prados Del Niza',NULL),
  ('Barrio','Prados Del Norte',NULL),
  ('Barrio','Prados del Oeste',NULL),
  ('Barrio','Prados Del Sur',NULL),
  ('Barrio','Praga',NULL),
  ('Barrio','Pucalpa I',NULL),
  ('Barrio','Pucalpa II',NULL),
  ('Barrio','Pucalpa III',NULL),
  ('Barrio','Puerta Del Sol',NULL),
  ('Barrio','Quebrada Gallinacera 2da Parte',NULL),
  ('Barrio','Quillacinga',NULL),
  ('Barrio','Quillotocto',NULL),
  ('Barrio','Quintas de San Pedro',NULL),
  ('Barrio','Quito López I',NULL),
  ('Barrio','Quito López II',NULL),
  ('Barrio','Quito López III',NULL),
  ('Barrio','Remansos del Norte',NULL)
on conflict (place_type, place_name) do nothing;

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Barrio','Rincón Colonial',NULL),
  ('Barrio','Rincón De Aranda',NULL),
  ('Barrio','Rincón Del Paraíso',NULL),
  ('Barrio','Rio Blanco',NULL),
  ('Barrio','Rio Blanco Que Termina Ojo De Agua',NULL),
  ('Barrio','Riviera',NULL),
  ('Barrio','Rosal Del Oriente',NULL),
  ('Barrio','Rosales I',NULL),
  ('Barrio','Rosales II',NULL),
  ('Barrio','Salazar Mejía',NULL),
  ('Barrio','Salida Al Sur- Urbano',NULL),
  ('Barrio','Salomón',NULL),
  ('Barrio','Salsipuedes',NULL),
  ('Barrio','San Agustín Centro',NULL),
  ('Barrio','San Albano',NULL),
  ('Barrio','San Andresito',NULL),
  ('Barrio','San Andrés',NULL),
  ('Barrio','San Antonio De Juanoy',NULL),
  ('Barrio','San Carlos',NULL),
  ('Barrio','San Diego',NULL),
  ('Barrio','San Diego Norte',NULL),
  ('Barrio','San Felipe',NULL),
  ('Barrio','San Germán',NULL),
  ('Barrio','San Ignacio',NULL),
  ('Barrio','San José',NULL),
  ('Barrio','San José Obrero',NULL),
  ('Barrio','San Juan de Anganoy',NULL),
  ('Barrio','San Juan de Dios I',NULL),
  ('Barrio','San Juan de Dios II',NULL),
  ('Barrio','San Juan De Los Pastos',NULL),
  ('Barrio','San Martin',NULL),
  ('Barrio','San Mateo',NULL),
  ('Barrio','San Miguel',NULL),
  ('Barrio','San Miguel De Jongovito',NULL),
  ('Barrio','San Pedro',NULL),
  ('Barrio','San Sebastián',NULL),
  ('Barrio','San Vicente',NULL),
  ('Barrio','Santa Ana',NULL),
  ('Barrio','Santa Bárbara',NULL),
  ('Barrio','Santa Catalina',NULL),
  ('Barrio','Santa Clara',NULL),
  ('Barrio','Santa Fe I',NULL),
  ('Barrio','Santa Fe II',NULL),
  ('Barrio','Santa Isabel',NULL),
  ('Barrio','Santa María',NULL),
  ('Barrio','Santa Matilde',NULL),
  ('Barrio','Santa Mónica',NULL),
  ('Barrio','Santa Rita',NULL),
  ('Barrio','Santacruz',NULL),
  ('Barrio','Santanita',NULL),
  ('Barrio','Santiago',NULL),
  ('Barrio','Sañudo',NULL),
  ('Barrio','Sector Pedagógico Avenida Oriental',NULL),
  ('Barrio','Sector San Juan Bosco',NULL),
  ('Barrio','SENA',NULL),
  ('Barrio','Sendoya',NULL),
  ('Barrio','Siete De Agosto',NULL),
  ('Barrio','Simón Bolívar',NULL),
  ('Barrio','Sindagua',NULL),
  ('Barrio','Sindamanoy',NULL),
  ('Barrio','Sol De Oriente',NULL),
  ('Barrio','Sumatambo',NULL),
  ('Barrio','Tamasagra I',NULL),
  ('Barrio','Tamasagra II',NULL),
  ('Barrio','Tequendama',NULL),
  ('Barrio','Termina Sector Peatonal 28',NULL),
  ('Barrio','Terranova',NULL),
  ('Barrio','Terrazas De Briceño',NULL),
  ('Barrio','Tescual',NULL),
  ('Barrio','Titán',NULL),
  ('Barrio','Torobajo',NULL),
  ('Barrio','Torres de Pubenza',NULL),
  ('Barrio','Universitario',NULL),
  ('Barrio','Uranización Zarama',NULL),
  ('Barrio','Valle De Atriz',NULL),
  ('Barrio','Valle Lili',NULL),
  ('Barrio','Venecia',NULL),
  ('Barrio','Veracruz',NULL),
  ('Barrio','Versalles',NULL),
  ('Barrio','Villa Adriana María',NULL),
  ('Barrio','Villa Aurora',NULL),
  ('Barrio','Villa Campanela',NULL),
  ('Barrio','Villa Campestre',NULL),
  ('Barrio','Villa Colombia',NULL),
  ('Barrio','Villa De Los Ríos',NULL),
  ('Barrio','Villa del Prado',NULL),
  ('Barrio','Villa Del Rio',NULL),
  ('Barrio','Villa Del Rosario',NULL),
  ('Barrio','Villa Elena',NULL),
  ('Barrio','Villa Guerrero - Villas Del Norte',NULL),
  ('Barrio','Villa Jardín',NULL),
  ('Barrio','Villa Jazmín',NULL),
  ('Barrio','Villa Lucia',NULL),
  ('Barrio','Villa María',NULL),
  ('Barrio','Villa Olímpica',NULL),
  ('Barrio','Villa Oriente',NULL),
  ('Barrio','Villa Recreo',NULL),
  ('Barrio','Villa Rocío',NULL),
  ('Barrio','Villa Sofía',NULL),
  ('Barrio','Villa Vergel',NULL)
on conflict (place_type, place_name) do nothing;

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Barrio','Villa Victoria',NULL),
  ('Barrio','Villa Ángela',NULL),
  ('Barrio','Villadocente',NULL),
  ('Barrio','Villaflor I',NULL),
  ('Barrio','Villaflor II',NULL),
  ('Barrio','Villas de San Rafael',NULL),
  ('Barrio','Vivienda Cristiana',NULL),
  ('Vereda','Aguapamba',NULL),
  ('Vereda','Alto Caldera',NULL),
  ('Vereda','Alto Casanare',NULL),
  ('Vereda','Alto San Fernando',NULL),
  ('Vereda','Alto San Pedro',NULL),
  ('Vereda','Armenia',NULL),
  ('Vereda','Arrayán Alto',NULL),
  ('Vereda','Bajo Casanare',NULL),
  ('Vereda','Bella vista',NULL),
  ('Vereda','Bellavista',NULL),
  ('Vereda','Botana',NULL),
  ('Vereda','Botanilla',NULL),
  ('Vereda','Briceño',NULL),
  ('Vereda','Buenavista',NULL),
  ('Vereda','Buesaquillo alto',NULL),
  ('Vereda','Buesaquillo Centro (Cabecera)',NULL),
  ('Vereda','Cabrera Centro (Cabecera)',NULL),
  ('Vereda','Caldera Centro (Cabecera)',NULL),
  ('Vereda','Camino Real y Caracolito.',NULL),
  ('Vereda','Campo Alegre',NULL),
  ('Vereda','Canchala',NULL),
  ('Vereda','Carrizo',NULL),
  ('Vereda','Casapamba',NULL),
  ('Vereda','Castillo Loma',NULL),
  ('Vereda','Catambuco Centro (Cabecera)',NULL),
  ('Vereda','Cerotal',NULL),
  ('Vereda','Chachatoy',NULL),
  ('Vereda','Charguayaco',NULL),
  ('Vereda','Chavez',NULL),
  ('Vereda','Chuquimarca',NULL),
  ('Vereda','Concepción',NULL),
  ('Vereda','Cruz de Amarillo',NULL),
  ('Vereda','Cruz Loma',NULL),
  ('Vereda','Cubijan Alto',NULL),
  ('Vereda','Cubiján Bajo',NULL),
  ('Vereda','Cujacal alto villa julia',NULL),
  ('Vereda','Cujacal Centro',NULL),
  ('Vereda','Cujacal san Isidro',NULL),
  ('Vereda','Daza (Cabecera)',NULL),
  ('Vereda','Dolores Centro',NULL),
  ('Vereda','Dolores Retén',NULL),
  ('Vereda','Duarte',NULL),
  ('Vereda','El Barbero y la Playa',NULL),
  ('Vereda','El Campanero',NULL),
  ('Vereda','El Carmelo',NULL),
  ('Vereda','El Carmen',NULL),
  ('Vereda','El Común',NULL),
  ('Vereda','El Edén',NULL),
  ('Vereda','El Encano Centro (Cabecera)',NULL),
  ('Vereda','El Estero',NULL),
  ('Vereda','El Puerto',NULL),
  ('Vereda','El Rosal',NULL),
  ('Vereda','El Rosario',NULL),
  ('Vereda','El Socorro',NULL),
  ('Vereda','Fray Ezequiel',NULL),
  ('Vereda','Genoy (Cabecera)',NULL),
  ('Vereda','Guadalupe',NULL),
  ('Vereda','Gualmatan bajo y Avenida Fátima',NULL),
  ('Vereda','Gualmatán',NULL),
  ('Vereda','Gualmatán Alto',NULL),
  ('Vereda','Gualmatán Centro',NULL),
  ('Vereda','Huertecillas',NULL),
  ('Vereda','Jamondino Centro (Cabecera)',NULL),
  ('Vereda','Jongovito Centro',NULL),
  ('Vereda','Josefina',NULL),
  ('Vereda','Jurado',NULL),
  ('Vereda','La Alianza',NULL),
  ('Vereda','La Cadena',NULL),
  ('Vereda','La Cocha',NULL),
  ('Vereda','La Esperanza',NULL),
  ('Vereda','La Huecada',NULL),
  ('Vereda','La Josefina',NULL),
  ('Vereda','La Laguna Centro (Cabecera)',NULL),
  ('Vereda','La Merced',NULL),
  ('Vereda','La Paz y El Purgatorio.',NULL),
  ('Vereda','La Playa',NULL),
  ('Vereda','La Victoria',NULL),
  ('Vereda','Las Encinas',NULL),
  ('Vereda','Los Alisales',NULL),
  ('Vereda','Los Arrayanes',NULL),
  ('Vereda','Los LiRíos',NULL),
  ('Vereda','Los Ángeles',NULL),
  ('Vereda','Mapachico Centro (Cabecera)',NULL),
  ('Vereda','Mocondino Centro (Cabecera)',NULL),
  ('Vereda','Mocondino y Dolores',NULL),
  ('Vereda','Mojondinoy',NULL),
  ('Vereda','Mosquera',NULL),
  ('Vereda','Motilón',NULL),
  ('Vereda','Naranjal',NULL),
  ('Vereda','Nueva Betania',NULL),
  ('Vereda','Nueva Campiña',NULL),
  ('Vereda','Obonuco Centro (Cabecera)',NULL),
  ('Vereda','Pejendino Reyes',NULL)
on conflict (place_type, place_name) do nothing;

insert into public.territorial_catalog (place_type, place_name, division_name) values
  ('Vereda','Pinasaco',NULL),
  ('Vereda','Pradera Bajo',NULL),
  ('Vereda','Puerres',NULL),
  ('Vereda','Pullitopamba',NULL),
  ('Vereda','Ramos',NULL),
  ('Vereda','Romerillo',NULL),
  ('Vereda','San Antonio',NULL),
  ('Vereda','San Antonio de Acuyuyo',NULL),
  ('Vereda','San Antonio de Aranda',NULL),
  ('Vereda','San Antonio de Casanare',NULL),
  ('Vereda','San Cayetano',NULL),
  ('Vereda','San Felipe Alto',NULL),
  ('Vereda','San Felipe Bajo',NULL),
  ('Vereda','San Fernando Alto',NULL),
  ('Vereda','San Fernando Bajo',NULL),
  ('Vereda','San Fernando Centro Vereda (Cabecera)',NULL),
  ('Vereda','San Francisco',NULL),
  ('Vereda','San Francisco Briceño',NULL),
  ('Vereda','San Gabriel',NULL),
  ('Vereda','San Isidro',NULL),
  ('Vereda','San José',NULL),
  ('Vereda','San José de Casanare',NULL),
  ('Vereda','San José de Catambuco',NULL),
  ('Vereda','San Juan Alto',NULL),
  ('Vereda','San Juan Bajo',NULL),
  ('Vereda','San Juan De Anganoy Y Anganoy',NULL),
  ('Vereda','San Luis',NULL),
  ('Vereda','San Pedro',NULL),
  ('Vereda','Santa Barbara',NULL),
  ('Vereda','Santa Clara',NULL),
  ('Vereda','Santa Helena y Jamondino',NULL),
  ('Vereda','Santa Isabel',NULL),
  ('Vereda','Santa Rosa',NULL),
  ('Vereda','Santa Teresita y Santa Lucía',NULL),
  ('Vereda','Santamaría',NULL),
  ('Vereda','Santander',NULL),
  ('Vereda','Tamboloma',NULL),
  ('Vereda','Tescual',NULL),
  ('Vereda','Tosoabi',NULL),
  ('Vereda','Villa Campiña',NULL),
  ('Vereda','Villa María',NULL),
  ('Vereda','Vocacional',NULL)
on conflict (place_type, place_name) do nothing;

