// Migrated from the Power Pages territorial fallback catalog.
export const TERRITORIAL_CATALOG = {
  "Barrio": [
    "Avenida Santander",
    "Bombona",
    "Avenida Boyacá",
    "Caracha",
    "Centro",
    "Condominio Santiago",
    "El Churo",
    "El Cilindro",
    "El Parque",
    "El Portalito",
    "Hullaguanga",
    "La Panadería",
    "Las Américas",
    "Los Dos Puentes",
    "Marcos De La Rosa",
    "San Agustín Centro",
    "San Andrés",
    "San Andresito",
    "San José",
    "San José Obrero",
    "Santiago",
    "Aire Libre",
    "Alhambra",
    "Atahualpa",
    "Avenida Boyacá",
    "Avenida Champagnath",
    "Avenida Colombia",
    "Bella Vista",
    "Casa Bella",
    "Coliseo Cubierto",
    "El Olivo",
    "El Prado",
    "El Recuerdo",
    "Fátima",
    "Javeriano",
    "Julián Bucheli",
    "La Gran Colombia",
    "Las lunas I",
    "las lunas II",
    "Las Violetas I",
    "Las Violetas II",
    "Las Violetas III",
    "Las Violetas IV",
    "Los Abedules",
    "Los Álamos",
    "Los Balcones",
    "Los Olivos",
    "Medardo Bucheli",
    "Navarrete",
    "Normandía",
    "Parque Bolívar",
    "Salomón",
    "San Miguel",
    "Sector San Juan Bosco",
    "Villa Lucia",
    "iAlejandría",
    "Arnulfo Guerrero",
    "Caicedonia",
    "Camilo Torres",
    "Casa Loma",
    "El Ejido",
    "Guamuez",
    "José Antonio Galán",
    "La Esmeralda",
    "La Estrella",
    "Las Brisas",
    "Las Lajas",
    "Las Mercedes",
    "Los Pinos",
    "Mercedario",
    "Pie De Cuesta",
    "Pinar Del Rio",
    "Popular",
    "Pucalpa I",
    "Pucalpa II",
    "Pucalpa III",
    "Rosal Del Oriente",
    "Santa Bárbara",
    "Santa Catalina",
    "Santa Mónica",
    "Villa Oriente",
    "Villaflor I",
    "Villaflor II",
    "Albergue Del Sol",
    "Altos De Lorenzo",
    "Altos Del Campo",
    "Avenida Idema",
    "Belén",
    "Bernal",
    "Betania",
    "Chile",
    "Doce De Octubre I",
    "Doce De Octubre II",
    "El Porvenir",
    "El Rosario",
    "El Tejar",
    "El Triunfo",
    "La Paz",
    "Laureano Gómez",
    "Lorenzo De Aldana",
    "Los Elíseos",
    "Miraflores I",
    "Miraflores II",
    "Praga",
    "Puerta Del Sol",
    "Rincón Colonial",
    "San Germán",
    "San Juan De Los Pastos",
    "Santa Fe I",
    "Santa Fe II",
    "Santacruz",
    "Sendoya",
    "Siete De Agosto",
    "Villa Olímpica",
    "Villa Victoria",
    "Villadocente",
    "Altos De Chapalito I",
    "Altos De Chapalito II",
    "Altos De Chapalito III",
    "Antonio Nariño",
    "Cantarana",
    "Chambú I",
    "Chambú II",
    "Chapal",
    "Chapal II",
    "El Pilar",
    "El Progreso",
    "El Remanso",
    "Emilio Botero I",
    "Emilio Botero II",
    "Emilio Botero III",
    "Emilio Botero IV",
    "La Minga",
    "La Rosa",
    "La Vega",
    "Las Ferias",
    "Los Cristales",
    "Los Robles",
    "Madrigal",
    "María Isabel I",
    "María Isabel II",
    "María Isabel III",
    "Potrerillo",
    "Prados Del Sur",
    "Salida Al Sur- Urbano",
    "San Martin",
    "Santa Clara",
    "Venecia",
    "Villa Del Rio",
    "Vivienda Cristiana",
    "Agualongo",
    "Altamira",
    "Bachue",
    "Caicedo",
    "Ciudad Jardín",
    "Cooperativa Popular Nariñense",
    "El Estadio",
    "El Libertador",
    "Gilberto Pabón",
    "Granada I",
    "Granada II",
    "Granada III",
    "Granada IV",
    "Inem",
    "Jerusalén",
    "La Cruz",
    "La Palma",
    "Los Fundadores",
    "Luis Carlos Galán",
    "Mijitayo II",
    "Mijitayo",
    "Mijitayo Bajo",
    "Mirador De Niza",
    "Niza I",
    "Niza II",
    "Niza III",
    "Nueva Colombia",
    "Prados Del Niza",
    "Quillacinga",
    "Quito López I",
    "Quito López II",
    "Quito López III",
    "San Carlos",
    "San Miguel De Jongovito",
    "San Sebastián",
    "Santa Isabel",
    "Santanita",
    "Sumatambo",
    "Tamasagra I",
    "Tamasagra II",
    "Tequendama",
    "Valle Lili",
    "Villa De Los Ríos",
    "Achalay",
    "Avenida Panamericana",
    "Capusigra",
    "Castillos Del Norte",
    "Conjunto El Parque",
    "El Bosque",
    "El Edén",
    "El Rincón De La Aurora",
    "El Rincón De La Panamericana",
    "Francisco De La Villota",
    "La Aurora",
    "La Primavera",
    "Las Acacias",
    "Las Camelias",
    "Los Andes",
    "Los Hexágonos",
    "Rosales II",
    "Rosales I",
    "San Felipe",
    "San Ignacio",
    "Santa María",
    "Villa Aurora",
    "Villa Campanela",
    "Villa Sofía",
    "Villa Vergel",
    "Altamira – San Vicente",
    "Altavista",
    "Altos de la Colina",
    "Anganoy",
    "Arcos Iris",
    "Avenida Panamericana",
    "Balcones de Mariluz",
    "Bello Horizonte",
    "Colón",
    "Colpatria",
    "Conjunto San Diego",
    "El Remanso del Norte",
    "Gualcaloma",
    "Jorge Giraldo",
    "La Castellana",
    "La Cuesta",
    "La Pradera",
    "Las Margaritas",
    "Los Frailejones",
    "Los Héroes",
    "Los Laureles",
    "Los Urapanes",
    "Mariluz I",
    "Mariluz II",
    "Mariluz III",
    "Mirador de San Juan",
    "Miravalle",
    "Montemor",
    "Panamericano",
    "Panamericano II",
    "Panamericano I",
    "Portal de la Colina",
    "Prados del Oeste",
    "Quintas de San Pedro",
    "Remansos del Norte",
    "Salazar Mejía",
    "San Diego",
    "San Juan de Anganoy",
    "San Juan de Dios I",
    "San Juan de Dios II",
    "San Pedro",
    "San Vicente",
    "Sindamanoy",
    "Torres de Pubenza",
    "Veracruz",
    "Villa Jardín",
    "Villas de San Rafael",
    "Alto Juanoy",
    "Avenida Los Estudiantes",
    "Briceño",
    "Calatrava",
    "Camino Real",
    "Castilla",
    "Chapultepec",
    "Colonial",
    "Condominio Morasurco",
    "Conjunto Torobajo",
    "El Aljibe",
    "El Cerámico",
    "El Dorado",
    "El Mirador",
    "El Polvorín",
    "El Refugio",
    "Figueroa",
    "José Ignacio Zarama",
    "Juan XXIII",
    "Juanoy",
    "La Colina",
    "La Riviera",
    "Las Cuadras",
    "La Victoria",
    "Los Nogales",
    "Los Sauces",
    "Luis Brand",
    "Manaca",
    "Maridiaz",
    "Marsella",
    "Morasurco",
    "Nuevo Amanecer",
    "Palermo",
    "Pandiaco",
    "Parana",
    "Parque Infantil",
    "Pinos Del Norte",
    "Portal De La Colina",
    "Riviera",
    "San Antonio De Juanoy",
    "Santa Ana",
    "Santa Rita",
    "Sañudo",
    "Tequendama",
    "Terranova",
    "Terrazas De Briceño",
    "Titán",
    "Torobajo",
    "Universitario",
    "Uranización Zarama",
    "Valle De Atriz",
    "Versalles",
    "Villa María",
    "Villa Campestre",
    "Aranda",
    "Avenida Aranda",
    "Avenida Oriental",
    "Avenida Oriental Rio Pasto",
    "Buenos Aires",
    "Cementerio",
    "Condominio Bellavista",
    "Corazón De Jesús II",
    "Cra 27 A Del Barrio Centenario",
    "Destechados",
    "El Futuro",
    "El Portal De Aranda",
    "El Portal Del Norte",
    "El Rincón De Pasto",
    "El Rincón Del Rosario",
    "Juan Pablo II",
    "La Esperanza",
    "La Floresta",
    "Libertad",
    "Loma Del Carmen (Marquetalia)",
    "Marquetalia",
    "Niño Jesús De Praga",
    "Nueva Aranda",
    "Nuevo Horizonte",
    "Nuevo Sol",
    "Ocho De Marzo",
    "Prados Del Norte",
    "Quebrada Gallinacera 2da Parte",
    "Quillotocto",
    "Rincón De Aranda",
    "Rio Blanco",
    "Rio Blanco Que Termina Ojo De Agua",
    "San Albano",
    "Santa Matilde",
    "Sector Pedagógico Avenida Oriental",
    "Sol De Oriente",
    "Termina Sector Peatonal 28",
    "Tescual",
    "Villa Del Rosario",
    "Villa Guerrero - Villas Del Norte",
    "Alameda",
    "Alameda II",
    "Aquine I",
    "Aquine II",
    "Aquine III",
    "Aquine Alto",
    "Aquine IV",
    "Aquine Reservado",
    "Belalcázar",
    "Centenario",
    "Chico",
    "Ciudad Real",
    "Corazón De Jesús",
    "El Calvario",
    "El Común",
    "El Corralito",
    "Hospital Civil",
    "La Floresta",
    "La Lomita",
    "Los Alcázares",
    "Rincón Del Paraíso",
    "Salsipuedes",
    "Villa Elena",
    "Villa Jazmín",
    "Altos De La Carolina",
    "Balcones Del Este",
    "Campiña De Oriente",
    "Carlos Pizarro",
    "Cujacal Bajo",
    "El Manantial",
    "El Paraíso",
    "Fray Ezequiel Moreno Díaz",
    "Gualcala",
    "La Carolina",
    "La Florida",
    "La Josefina",
    "Las Orquídeas",
    "María Paz",
    "María Paz II",
    "Monserrat",
    "Parque De Baviera",
    "San Diego Norte",
    "San Mateo",
    "SENA",
    "Simón Bolívar",
    "Sindagua",
    "Villa Colombia",
    "Villa Adriana María",
    "Villa Ángela",
    "Villa del Prado",
    "Villa Recreo",
    "Villa Rocío"
  ],
  "Vereda": [
    "Catambuco Centro (Cabecera)",
    "El Campanero",
    "Bellavista",
    "Botana",
    "La Merced",
    "Botanilla",
    "La Victoria",
    "San Antonio de Acuyuyo",
    "Guadalupe",
    "San José de Casanare",
    "San Antonio de Casanare",
    "Chavez",
    "Alto Casanare",
    "San José de Catambuco",
    "Cruz de Amarillo",
    "Santamaría",
    "Cubiján Bajo",
    "Cubijan Alto",
    "Fray Ezequiel",
    "San Isidro",
    "Gualmatán",
    "Huertecillas",
    "Nueva Betania",
    "Vocacional",
    "Gualmatán Alto",
    "Gualmatán Centro",
    "Gualmatan bajo y Avenida Fátima",
    "Genoy (Cabecera)",
    "El Edén",
    "La Cocha",
    "Pullitopamba",
    "Aguapamba",
    "Castillo Loma",
    "Nueva Campiña",
    "Charguayaco",
    "Bella vista",
    "Mapachico Centro (Cabecera)",
    "Villa María",
    "El Rosal",
    "Briceño",
    "La Victoria",
    "San Cayetano",
    "San Francisco Briceño",
    "Los LiRíos",
    "San Juan De Anganoy Y Anganoy",
    "Obonuco Centro (Cabecera)",
    "Santander",
    "San Felipe Alto",
    "San Felipe Bajo",
    "San Antonio",
    "Bellavista",
    "La Playa",
    "Mosquera",
    "Jurado",
    "Santa Barbara",
    "Concepción",
    "Los Ángeles",
    "La Esperanza",
    "Las Encinas",
    "Cerotal",
    "Los Alisales",
    "La Laguna Centro (Cabecera)",
    "Aguapamba",
    "San Luis",
    "Alto San Pedro",
    "El Barbero y la Playa",
    "San Fernando Alto",
    "San Fernando Bajo",
    "Dolores Centro",
    "Buesaquillo Centro (Cabecera)",
    "La Alianza",
    "San José",
    "San Francisco",
    "La Huecada",
    "Pejendino Reyes",
    "El Carmelo",
    "Tamboloma",
    "Buesaquillo alto",
    "Cujacal Centro",
    "La Josefina",
    "Cujacal san Isidro",
    "Cujacal alto villa julia",
    "Daza (Cabecera)",
    "San Juan Alto",
    "San Juan Bajo",
    "Tosoabi",
    "Chachatoy",
    "Pinasaco",
    "Tescual",
    "San Antonio de Aranda",
    "La Josefina",
    "Caldera Centro (Cabecera)",
    "Alto Caldera",
    "San Antonio",
    "Pradera Bajo",
    "Arrayán Alto",
    "Los Arrayanes",
    "Villa Campiña",
    "El Encano Centro (Cabecera)",
    "Ramos",
    "Romerillo",
    "Motilón",
    "Carrizo",
    "Casapamba",
    "El Socorro",
    "Bellavista",
    "El Puerto",
    "San José",
    "Campo Alegre",
    "Santa Clara",
    "Santa Rosa",
    "Mojondinoy",
    "Naranjal",
    "El Estero",
    "Santa Isabel",
    "Santa Teresita y Santa Lucía",
    "Cabrera Centro (Cabecera)",
    "Buenavista",
    "Duarte",
    "La Paz y El Purgatorio.",
    "San Fernando Centro Vereda (Cabecera)",
    "Dolores Retén",
    "El Común",
    "Alto San Fernando",
    "La Cadena",
    "Camino Real y Caracolito.",
    "Mocondino Centro (Cabecera)",
    "Canchala",
    "Puerres",
    "Mocondino y Dolores",
    "Jamondino Centro (Cabecera)",
    "El Rosario",
    "Santa Helena y Jamondino",
    "Jongovito Centro",
    "Chuquimarca",
    "Cruz Loma",
    "Josefina",
    "Armenia",
    "San Pedro",
    "San Francisco",
    "El Socorro",
    "El Carmen",
    "Bajo Casanare",
    "San Gabriel"
  ]
};

export const DIVISIONS = [
  "Comuna 1",
  "Comuna 2",
  "Comuna 3",
  "Comuna 4",
  "Comuna 5",
  "Comuna 6",
  "Comuna 7",
  "Comuna 8",
  "Comuna 9",
  "Comuna 10",
  "Comuna 11",
  "Comuna 12",
  "Catambuco",
  "Gualmatán",
  "Genoy",
  "Mapachico",
  "Obonuco",
  "Santa Bárbara",
  "La Laguna",
  "Buesaquillo",
  "Morasurco",
  "La Caldera",
  "El Encano",
  "Cabrera",
  "San Fernando",
  "Mocondino",
  "Jamondino",
  "Jongovito",
  "El Socorro"
];
